server:
  port: 8081
spring:
  application:
    name: user-microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/fast_market
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false